// 页面中英文文案：每个字段单独一行，修改引号里的文字即可。
// 摄影专题和照片请编辑 gallery-data.js；项目经历请编辑 portfolio-data.js。
window.translations = {
  en: {
    job3Date: "Aug 2024 — Oct 2024",
    job3Place: "Part-time",
    job3Title: "Website Development & Digital Content",
    job3Company: "Outdoor furniture & equipment business",
    job3Bullet1: "Built an independent e-commerce website and prepared its content for an outdoor furniture and equipment business.",
    job3Bullet2: "Shot and edited videos, and published promotional content across TikTok, Instagram, and YouTube.",
    job3Bullet3: "Produced weekly visual reports analysing content performance and click data to review trends.",
    homeWorkTitle: "Work & practice",
    homeWorkBody: "I have three years of experience in business systems and application support, alongside hands-on work in front-end development and e-commerce websites.",
    homeWorkLink: "More about my experience",
    homeLifeTitle: "Outside the screen",
    homeLifeBody: "Photography and hiking are part of my life outside work and study. I helped photograph a New Year's Eve event, and I'd like to keep exploring natural, relaxed portraits.",
    homeLifeLink: "Photography notes",
    pageTitle: "Hu Jiao — Computer Science & Digital Projects",
    pageDescription: "Hu Jiao — computer science student working across practical software, business systems, and digital projects.",
    skip: "Skip to main content",
    navLabel: "Primary navigation",
    menuLabel: "Navigation menu",
    languageLabel: "Language",
    factsLabel: "Profile facts",
    projectTechLabel: "Project technologies",
    brandLabel: "Hu Jiao, home",
    closePreview: "Close preview",
    navProfile: "Home",
    navExperience: "Experience",
    navSkills: "Skills",
    navProject: "Projects",
    navGallery: "Photography",
    navEducation: "Education",
    contactShort: "Email",
    profileName: "Hu Jiao",
    locationLabel: "Based in",
    location: "Sydney, Australia",
    educationLabel: "Studying",
    educationFact: "Master of Computer Science<br>The University of Sydney",
    focusLabel: "Focus",
    focusFact: "Business systems, e-commerce operations, user support, and visual media",
    languagesLabel: "Languages",
    languagesFact: "English and Mandarin Chinese",
    profileLabel: "Personal profile",
    heroTitle: "Exploring ideas. Making things.",
    heroBody1: "I'm a Master of Computer Science student at the University of Sydney. I enjoy exploring across disciplines and bringing ideas to life with technology and AI.",
    heroBody2: "This is a space for my work, independent projects, and photography.",
    experienceLabel: "Professional background",
    experienceTitle: "Experience",
    job1Date: "3 years",
    job1Place: "Full-time",
    job1Title: "Business Systems & Workflow Coordination",
    job1Company: "Western Impression Cultural Tourism Co., Ltd.",
    job1Bullet1: "Managed internal OA and workflow systems, configuring approval processes to support day-to-day business operations.",
    job1Bullet2: "Translated cross-department business requirements into digital approval workflows and system configuration requirements.",
    job1Bullet3: "Consolidated user feedback into actionable change requests and coordinated follow-up with external technical teams.",
    job1Bullet4: "Worked with business and finance teams to resolve workflow issues and keep operations moving.",
    job2Date: "May 2025 — Jul 2025",
    job2Place: "Remote",
    job2Title: "Front-End & Product Operations Assistant",
    job2Company: "Zion · Part-time",
    job2Bullet1: "Contributed to front-end development and interface implementation using HTML and CSS.",
    job2Bullet2: "Supported product operations alongside front-end work in a startup environment.",
    skillsLabel: "Working knowledge",
    skillsTitle: "Skills",
    businessSystems: "Business systems",
    businessSystemsList: "OA systems · Workflow configuration · Digital approval processes",
    development: "Development",
    dataTools: "Data & tools",
    professionalSkills: "Professional",
    professionalSkillsList: "User support · Requirements clarification · Documentation · Stakeholder communication",
    projectLabel: "Selected work",
    projectTitle: "Projects",
    galleryTitle: "Photography",
    galleryIntro: "Outside work and study, I enjoy photography and hiking. I helped photograph a New Year’s Eve event, and I’m interested in trying relaxed, natural portrait photography.",
    educationSectionLabel: "Academic background",
    educationTitle: "Education",
    mastersDate: "Aug 2026 — Present",
    mastersName: "Master of Computer Science",
    mastersSchool: "The University of Sydney · Sydney, Australia",
    bachelorsDate: "Sep 2019 — Jul 2023",
    bachelorsName: "Bachelor of Computer Science",
    bachelorsSchool: "Chengdu University of Technology & Oxford Brookes University",
    contactLabel: "Get in touch",
    contactTitle: "Let’s start a conversation.",
    contactBody: "I’m always glad to talk about practical software, digital projects, business systems, and opportunities to learn or collaborate.",
    contactButton: "Email Hu Jiao",
    backToTop: "Back to top"
  },
  "zh-CN": {
    job3Date: "2024 年 8 月 — 10 月",
    job3Place: "兼职",
    job3Title: "独立站搭建与数字内容运营",
    job3Company: "户外家具与用品商家",
    job3Bullet1: "为户外家具与用品商家搭建独立网站，并完成网站内容制作。",
    job3Bullet2: "独立拍摄、剪辑视频，在 TikTok、Instagram 和 YouTube 发布宣传内容。",
    job3Bullet3: "每周制作可视化数据报告，分析内容表现与点击数据，梳理变化趋势。",
    homeWorkTitle: "工作与实践",
    homeWorkBody: "我有三年的业务系统与应用支持经验，也参与过前端开发和电商独立站搭建。",
    homeWorkLink: "了解我的经历",
    homeLifeTitle: "屏幕之外",
    homeLifeBody: "工作和学习之外，我喜欢摄影与徒步。我曾参与一次跨年活动的现场摄影，也想继续尝试轻松、自然的人像拍摄。",
    homeLifeLink: "摄影记录",
    pageTitle: "胡娇 — 计算机与数字项目",
    pageDescription: "胡娇的双语个人网站：计算机科学、实用软件、业务系统与数字项目。",
    skip: "跳到主要内容",
    navLabel: "主导航",
    menuLabel: "导航菜单",
    languageLabel: "语言",
    factsLabel: "个人信息",
    projectTechLabel: "项目技术",
    brandLabel: "胡娇，首页",
    closePreview: "关闭预览",
    navProfile: "首页",
    navExperience: "经历",
    navSkills: "技能",
    navProject: "项目",
    navGallery: "摄影",
    navEducation: "教育",
    contactShort: "邮件",
    profileName: "胡娇",
    locationLabel: "现居",
    location: "澳大利亚悉尼",
    educationLabel: "在读",
    educationFact: "计算机科学硕士<br>悉尼大学",
    focusLabel: "关注方向",
    focusFact: "业务系统、电商运营、用户支持与视觉媒体",
    languagesLabel: "语言",
    languagesFact: "中文与英文",
    profileLabel: "个人简介",
    heroTitle: "探索想法，动手创造。",
    heroBody1: "我目前在悉尼大学攻读计算机科学硕士，喜欢借助技术与人工智能探索不同领域，在实践中学习，把想法变成现实。",
    heroBody2: "这里记录我的工作经历、独立项目与摄影。",
    experienceLabel: "专业背景",
    experienceTitle: "工作经历",
    job1Date: "三年",
    job1Place: "全职",
    job1Title: "业务系统与流程协调",
    job1Company: "西部印象文化旅游股份有限公司",
    job1Bullet1: "负责内部办公自动化与工作流系统的日常管理及配置，支持各部门业务流程运转。",
    job1Bullet2: "梳理跨部门审批需求，将业务规则转化为数字化流程及系统配置要求。",
    job1Bullet3: "汇总用户反馈，形成明确的变更需求，并协调外部技术团队跟进。",
    job1Bullet4: "对接业务部门与财务团队，协同处理流程使用中的问题。",
    job2Date: "2025 年 5 月 — 2025 年 7 月",
    job2Place: "远程",
    job2Title: "前端与产品运营助理",
    job2Company: "Zion · 兼职",
    job2Bullet1: "使用 HTML 与 CSS 参与前端开发和界面实现。",
    job2Bullet2: "在初创团队中配合前端工作，参与产品运营。",
    skillsLabel: "知识与能力",
    skillsTitle: "技能",
    businessSystems: "业务系统",
    businessSystemsList: "OA 系统 · 工作流配置 · 数字化审批流程",
    development: "开发",
    dataTools: "数据与工具",
    professionalSkills: "专业能力",
    professionalSkillsList: "用户支持 · 需求梳理 · 文档编写 · 利益相关者沟通",
    projectLabel: "代表作品",
    projectTitle: "项目",
    galleryTitle: "摄影记录",
    galleryIntro: "工作和学习之外，我喜欢摄影与徒步。我曾参与一次跨年活动的现场摄影，也想继续尝试轻松、自然的人像拍摄。",
    educationSectionLabel: "学术背景",
    educationTitle: "教育经历",
    mastersDate: "2026 年 8 月 — 至今",
    mastersName: "计算机科学硕士",
    mastersSchool: "悉尼大学 · 澳大利亚悉尼",
    bachelorsDate: "2019 年 9 月 — 2023 年 7 月",
    bachelorsName: "计算机科学学士",
    bachelorsSchool: "成都理工大学 & 牛津布鲁克斯大学",
    contactLabel: "联系我",
    contactTitle: "欢迎与我交流。",
    contactBody: "欢迎与我交流实用软件、数字项目、业务系统，以及学习或合作机会。",
    contactButton: "发送邮件给胡娇",
    backToTop: "返回顶部"
  }
};
